// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmegscxlwywkuzrgyouh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tZWdzY3hsd3l3a3V6cmd5b3VoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NDQ0ODUsImV4cCI6MjA2MjUyMDQ4NX0.6Ce1wG2tkZ_8XpeChmuUNPSM_bl3tMgzpXfMWQ_In5o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);