
name: Website Backup

on:
  schedule:
    # تنفيذ كل يوم في الساعة 02:00 صباحاً
    - cron: '0 2 * * *'
  workflow_dispatch: # للسماح بالتشغيل اليدوي

jobs:
  backup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Set up Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest
          
      - name: Create backup folders
        run: |
          mkdir -p backups/database
          mkdir -p backups/storage
          mkdir -p backups/source
          
      - name: Backup database
        run: |
          supabase db dump -f backups/database/backup-${{ github.run_id }}.sql
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: "nmegscxlwywkuzrgyouh"
          
      - name: Backup source code
        run: |
          zip -r backups/source/code-backup-${{ github.run_id }}.zip ./ -x "*/node_modules/*" "*/dist/*" "*/build/*" "*/.git/*"
          
      - name: Upload backup to GitHub artifacts
        uses: actions/upload-artifact@v3
        with:
          name: website-backup-${{ github.run_id }}
          path: backups/
          retention-days: 30
          
      - name: Upload backup to S3 (Optional)
        if: ${{ secrets.AWS_ACCESS_KEY_ID != '' }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Copy backups to S3
        if: ${{ secrets.AWS_ACCESS_KEY_ID != '' }}
        run: |
          aws s3 cp backups s3://${{ secrets.BACKUP_BUCKET }}/$(date +%Y-%m-%d)/ --recursive
